/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login para todos os perfis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login realizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cadastro/vendedor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastro de novo vendedor (inicia trial) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CadastroVendedorRequest"];
                };
            };
            responses: {
                /** @description Vendedor criado, trial iniciado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cadastro/comprador": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastro de comprador via código de convite */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CadastroCompradorRequest"];
                };
            };
            responses: {
                /** @description Comprador criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recuperar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envia email de recuperação de senha */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecuperarSenhaRequest"];
                };
            };
            responses: {
                /** @description Email enviado (mesmo se o email não existir, por segurança) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/redefinir-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redefine senha via token do email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RedefinirSenhaRequest"];
                };
            };
            responses: {
                /** @description Senha redefinida */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPIs do vendedor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardVendedorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/compradores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista compradores do vendedor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompradorResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Cadastra novo comprador */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompradorRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompradorResponse"];
                    };
                };
                429: components["responses"]["LimitExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/compradores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Detalhe do comprador */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompradorResponse"];
                    };
                };
            };
        };
        /** Atualiza comprador */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompradorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompradorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Remove comprador */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removido */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/compradores/{id}/convite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gera ou regenera código de convite para o portal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            codigoConvite?: string;
                            linkConvite?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/compradores/{id}/historico": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Histórico de compras de um comprador */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompradorHistoricoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista produtos */
        get: {
            parameters: {
                query?: {
                    categoria?: components["schemas"]["Categoria"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProdutoResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria produto */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProdutoRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProdutoResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/produtos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Detalhe do produto */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProdutoResponse"];
                    };
                };
            };
        };
        /** Atualiza produto */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProdutoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProdutoResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Remove produto */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removido */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/produtos/{id}/foto": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Faz upload da foto do produto */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        foto?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            fotoUrl?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/pacotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pacotes do vendedor */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["StatusPacote"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PacoteResumoResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria pacote */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PacoteRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PacoteResumoResponse"];
                    };
                };
                429: components["responses"]["LimitExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/pacotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Detalhe do pacote */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PacoteDetalheResponse"];
                    };
                };
            };
        };
        /** Atualiza pacote */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PacoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PacoteResumoResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/pacotes/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza status do pacote */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AtualizarStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PacoteResumoResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/vendedor/pacotes/{id}/resumo-financeiro": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Resumo financeiro detalhado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumoFinanceiroResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/pacotes/{id}/itens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Itens do pacote agrupados por comprador */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItensPorCompradorResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Adiciona item ao pacote */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderItemRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/pacotes/{id}/itens/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                itemId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Atualiza item */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderItemUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderItemResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Remove item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removido */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/frete/tabela": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista faixas de frete */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FaixaFreteResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Cadastra faixa de frete */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FaixaFreteRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FaixaFreteResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/frete/calcular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calcula frete para peso e tipo de envio */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CalcularFreteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalcularFreteResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/orcamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de orçamentos salvos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrcamentoResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Salva um orçamento calculado */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrcamentoRequest"];
                };
            };
            responses: {
                /** @description Salvo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrcamentoResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/orcamentos/simular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simula custo sem salvar */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrcamentoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrcamentoResultadoResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendedor/conta/plano": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plano atual e uso dos limites */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plano?: components["schemas"]["PlanoResponse"];
                            uso?: components["schemas"]["UsoPlanoPorcentagem"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/meus-pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard e lista de pedidos do comprador autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeusPedidosResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/meus-pedidos/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        /** Detalhe de um pedido específico */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PedidoCompradorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas globais da plataforma */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardAdminResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os vendedores */
        get: {
            parameters: {
                query?: {
                    plano?: components["schemas"]["NomePlano"];
                    status?: "TRIAL" | "ATIVO" | "SUSPENSO" | "CANCELADO";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantAdminResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Detalhe do vendedor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantAdminResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{id}/suspender": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspende conta do vendedor */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/tenants/{id}/reativar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reativa conta suspensa */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/tenants/{id}/plano": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera plano do vendedor manualmente */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        plano: components["schemas"]["NomePlano"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "VENDEDOR" | "COMPRADOR" | "ADMIN";
        /** @enum {string} */
        Categoria: "ROUPAS" | "TENIS" | "ELETRONICO" | "OUTROS";
        /** @enum {string} */
        StatusPacote: "RASCUNHO" | "AGUARDANDO_ENVIO" | "EM_VIAGEM" | "ALFANDEGA" | "TRANSITO" | "ENTREGUE" | "FINALIZADO";
        /** @enum {string} */
        TipoEnvio: "EXPRESSA" | "ECONOMICA";
        /** @enum {string} */
        NomePlano: "GRATUITO" | "BASICO" | "PRO" | "ENTERPRISE";
        /** @enum {string} */
        StatusPagamento: "PENDENTE" | "PAGO" | "PARCIAL";
        LoginRequest: {
            /** Format: email */
            email: string;
            senha: string;
        };
        LoginResponse: {
            accessToken?: string;
            /** @default Bearer */
            tokenType: string;
            /** @description Segundos até expirar */
            expiresIn?: number;
            usuario?: components["schemas"]["UsuarioResumoResponse"];
        };
        CadastroVendedorRequest: {
            nome: string;
            /** Format: email */
            email: string;
            /** @description Mín 8 chars, 1 maiúscula, 1 número, 1 especial */
            senha: string;
        };
        CadastroCompradorRequest: {
            nome: string;
            /** Format: email */
            email: string;
            senha: string;
            telefone?: string;
            /** @description Código gerado pelo vendedor */
            codigoConvite: string;
        };
        RecuperarSenhaRequest: {
            /** Format: email */
            email: string;
        };
        RedefinirSenhaRequest: {
            token: string;
            novaSenha: string;
        };
        UsuarioResumoResponse: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            email?: string;
            role?: components["schemas"]["Role"];
            /** Format: int64 */
            tenantId?: number | null;
        };
        PlanoResponse: {
            nome?: components["schemas"]["NomePlano"];
            /** @description null = ilimitado */
            maxPacotesMes?: number | null;
            maxCompradores?: number | null;
            maxProdutos?: number | null;
            portalCompradorIncluido?: boolean;
            exportacaoIncluida?: boolean;
            /** Format: double */
            precoMensalBrl?: number;
        };
        UsoPlanoPorcentagem: {
            pacotesMesUsados?: number;
            pacotesMesLimite?: number | null;
            compradoresUsados?: number;
            compradoresLimite?: number | null;
            produtosUsados?: number;
            produtosLimite?: number | null;
        };
        CompradorRequest: {
            nome: string;
            /** Format: email */
            email?: string;
            telefone?: string;
        };
        CompradorResponse: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            email?: string;
            telefone?: string;
            totalPedidos?: number;
            /** Format: double */
            totalGastoBrl?: number;
            /** Format: double */
            totalPendenteBrl?: number;
            /** Format: double */
            lucroGeradoBrl?: number;
            /** @description Código para o comprador se cadastrar no portal */
            codigoConvitePortal?: string;
        };
        CompradorHistoricoResponse: {
            comprador?: components["schemas"]["CompradorResponse"];
            totalPedidos?: number;
            /** Format: double */
            totalPagoBrl?: number;
            /** Format: double */
            totalPendenteBrl?: number;
            pedidos?: components["schemas"]["PedidoCompradorResponse"][];
        };
        ProdutoRequest: {
            nome: string;
            categoria: components["schemas"]["Categoria"];
            /** Format: double */
            custoYuan: number;
            /** Format: double */
            custoCompraYuan: number;
            /**
             * Format: double
             * @default 0
             */
            freteVendedorYuan: number;
            pesoGramas: number;
            descricao?: string;
            /** @description URL da foto após upload */
            fotoUrl?: string;
        };
        ProdutoResponse: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            categoria?: components["schemas"]["Categoria"];
            /** Format: double */
            custoYuan?: number;
            /** Format: double */
            custoCompraYuan?: number;
            /** Format: double */
            freteVendedorYuan?: number;
            pesoGramas?: number;
            descricao?: string;
            fotoUrl?: string | null;
        };
        PacoteRequest: {
            nome: string;
            tipoEnvio?: components["schemas"]["TipoEnvio"];
            /**
             * Format: double
             * @description Quantos yuan equivalem a 1 BRL (ex.: 1.24 significa R$1 = ¥1,24).
             * @example 1.24
             */
            cambio?: number;
            /**
             * Format: double
             * @default 0
             */
            taxaAlfandegariaBrl: number;
            /** Format: date */
            dataEnvio?: string;
            observacoes?: string;
        };
        PacoteResumoResponse: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            status?: components["schemas"]["StatusPacote"];
            tipoEnvio?: components["schemas"]["TipoEnvio"];
            pesoTotalGramas?: number;
            /** Format: double */
            custoTotalBrl?: number;
            /** Format: double */
            receitaTotalBrl?: number;
            /** Format: double */
            margemPercentual?: number;
            totalCompradores?: number;
            totalItens?: number;
            /**
             * Format: double
             * @description Quantos yuan equivalem a 1 BRL usado no pacote.
             */
            cambio?: number;
            /** Format: date-time */
            dataCriacao?: string;
            /** Format: date */
            dataEnvio?: string;
        };
        PacoteDetalheResponse: components["schemas"]["PacoteResumoResponse"] & {
            /** Format: double */
            taxaCssbuyYuan?: number;
            /** Format: double */
            freteInternacionalYuan?: number;
            /** Format: double */
            freteInternacionalBrl?: number;
            /** Format: double */
            taxaAlfandegariaBrl?: number;
            itensPorComprador?: components["schemas"]["ItensPorCompradorResponse"][];
            observacoes?: string;
        };
        AtualizarStatusRequest: {
            status: components["schemas"]["StatusPacote"];
        };
        OrderItemRequest: {
            /** Format: int64 */
            compradorId: number;
            /** Format: int64 */
            produtoId: number;
            /** @default 1 */
            quantidade: number;
            /** Format: double */
            precoVendaBrl: number;
            statusPagamento?: components["schemas"]["StatusPagamento"];
        };
        OrderItemUpdateRequest: {
            quantidade?: number;
            /** Format: double */
            precoVendaBrl?: number;
            statusPagamento?: components["schemas"]["StatusPagamento"];
        };
        OrderItemResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            compradorId?: number;
            compradorNome?: string;
            produto?: components["schemas"]["ProdutoResponse"];
            quantidade?: number;
            /** Format: double */
            precoVendaBrl?: number;
            /** Format: double */
            custoRateadoBrl?: number;
            /** Format: double */
            lucroItemBrl?: number;
            /** Format: double */
            proporcaoPeso?: number;
            statusPagamento?: components["schemas"]["StatusPagamento"];
        };
        ItensPorCompradorResponse: {
            /** Format: int64 */
            compradorId?: number;
            compradorNome?: string;
            totalItens?: number;
            pesoTotalGramas?: number;
            /** Format: double */
            subtotalCustoBrl?: number;
            /** Format: double */
            subtotalVendaBrl?: number;
            /** Format: double */
            lucroBrl?: number;
            /** Format: double */
            margemPercentual?: number;
            /** Format: double */
            totalPendenteBrl?: number;
            itens?: components["schemas"]["OrderItemResponse"][];
        };
        MeusPedidosResponse: {
            totalPedidos?: number;
            /** Format: double */
            totalPagoBrl?: number;
            /** Format: double */
            totalPendenteBrl?: number;
            pedidos?: components["schemas"]["PedidoCompradorResponse"][];
        };
        PedidoCompradorResponse: {
            /** Format: int64 */
            itemId?: number;
            produto?: components["schemas"]["ProdutoResponse"];
            quantidade?: number;
            /** Format: double */
            precoVendaBrl?: number;
            statusPacote?: components["schemas"]["StatusPacote"];
            statusPagamento?: components["schemas"]["StatusPagamento"];
            /** Format: date-time */
            dataPacote?: string;
            nomeVendedor?: string;
        };
        ResumoFinanceiroResponse: {
            /** Format: int64 */
            pacoteId?: number;
            /**
             * Format: double
             * @description Câmbio utilizado na forma BRL->CNY (R$1 = ¥X).
             */
            cambioUtilizado?: number;
            /** Format: double */
            custoTotalYuan?: number;
            /** Format: double */
            custoTotalBrl?: number;
            /** Format: double */
            receitaTotalBrl?: number;
            /** Format: double */
            lucroBrl?: number;
            /** Format: double */
            margemPercentual?: number;
            /** Format: double */
            freteInternacionalYuan?: number;
            /** Format: double */
            freteInternacionalBrl?: number;
            /** Format: double */
            taxaCssbuyYuan?: number;
            /** Format: double */
            taxaCssbuyBrl?: number;
            /** Format: double */
            taxaAlfandegariaBrl?: number;
            compradores?: components["schemas"]["ItensPorCompradorResponse"][];
        };
        FaixaFreteRequest: {
            tipoEnvio: components["schemas"]["TipoEnvio"];
            pesoMinGramas: number;
            pesoMaxGramas: number;
            /** Format: double */
            custoYuan: number;
        };
        FaixaFreteResponse: components["schemas"]["FaixaFreteRequest"] & {
            /** Format: int64 */
            id?: number;
        };
        CalcularFreteRequest: {
            tipoEnvio: components["schemas"]["TipoEnvio"];
            pesoGramas: number;
        };
        CalcularFreteResponse: {
            /** Format: double */
            custoYuan?: number;
            faixaAplicada?: components["schemas"]["FaixaFreteResponse"];
        };
        OrcamentoRequest: {
            nomeProduto: string;
            categoria?: components["schemas"]["Categoria"];
            /** Format: double */
            custoYuan: number;
            /**
             * Format: double
             * @default 0
             */
            freteVendedorYuan: number;
            /**
             * Format: double
             * @default 0
             */
            freteInternacionalYuan: number;
            /**
             * Format: double
             * @default 0
             */
            taxaCssbuyYuan: number;
            /**
             * Format: double
             * @default 0
             */
            taxaAlfandegariaBrl: number;
            pesoGramas: number;
            /**
             * Format: double
             * @description Quantos yuan equivalem a 1 BRL (ex.: 1.24 significa R$1 = ¥1,24).
             * @example 1.24
             */
            cambio: number;
            /** Format: double */
            precoVendaBrl?: number;
        };
        OrcamentoResultadoResponse: {
            /** Format: double */
            custoProdutoBrl?: number;
            /** Format: double */
            custeFreteVendedorBrl?: number;
            /** Format: double */
            custeFreteInternacionalBrl?: number;
            /** Format: double */
            custoCssbuyBrl?: number;
            /** Format: double */
            taxaAlfandegariaBrl?: number;
            /** Format: double */
            custoTotalBrl?: number;
            /** Format: double */
            precoVendaBrl?: number;
            /** Format: double */
            lucroBrl?: number;
            /** Format: double */
            margemPercentual?: number;
            /** Format: double */
            precoSugeridoMargem20?: number;
            /** Format: double */
            precoSugeridoMargem30?: number;
        };
        OrcamentoResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            dataCriacao?: string;
        } & components["schemas"]["OrcamentoRequest"] & components["schemas"]["OrcamentoResultadoResponse"];
        DashboardVendedorResponse: {
            /** Format: double */
            totalReceberBrl?: number;
            compradoresPendentes?: number;
            /** Format: double */
            lucroTotalBrl?: number;
            totalPacotes?: number;
            totalCompradoresUnicos?: number;
            /** Format: double */
            ticketMedioBrl?: number;
            usoPlano?: components["schemas"]["UsoPlanoPorcentagem"];
            pacotesRecentes?: components["schemas"]["PacoteResumoResponse"][];
        };
        DashboardAdminResponse: {
            totalTenants?: number;
            tenantsPagantes?: number;
            /** Format: double */
            mrrBrl?: number;
            novosCadastros30Dias?: number;
            totalCompradores?: number;
            totalPacotesPlataforma?: number;
        };
        TenantAdminResponse: {
            /** Format: int64 */
            id?: number;
            nomeVendedor?: string;
            email?: string;
            plano?: components["schemas"]["NomePlano"];
            /** @enum {string} */
            statusConta?: "TRIAL" | "ATIVO" | "SUSPENSO" | "CANCELADO";
            /** Format: date-time */
            dataCadastro?: string;
            /** Format: date-time */
            ultimoAcesso?: string;
            totalPacotes?: number;
            totalCompradores?: number;
            /** Format: double */
            mrrBrl?: number;
        };
        ErrorResponse: {
            status?: number;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ValidationErrorResponse: {
            status?: number;
            message?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: {
        /** @description Recurso não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Erro de validação */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Token inválido ou ausente */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Sem permissão para este recurso */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Limite do plano atingido */
        LimitExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
